# This is a basic workflow to help you get started with Actions
# TODO only runs for 60 days without changes in the repo https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
name: schedule

# Controls when the workflow will run
on:
  schedule:
    - cron: '30 12 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, daily - cronjob
